### ISSUE TITLE
I can't start xfce anymore 

### ISSUE THREAD

**Issue by NaekiXD** [OkJacket2022/R36S-Xorg#1]
Hello, since I installed it everything had worked well for me but now it started to fail and it didn't let me start xfce, the last time it let me in it gave an error that I couldn't start and that I needed to contact the administrator. just as I was writing this it let me start it but I'll let you know if it happens again

**Comment by OkJacket2022** [comment]
Hi [MolkOficial](https://github.com/MolkOficial), as I said in the post, it's very buggy. From my tests the "contact the administrator" appears if you open XFCE too soon after booting up the device (the emulationstation GUI starts before the system has loaded all the files from Xorg, or something like this). 
If you give it some time to load before opening XFCE it should work fine (the exact time is when a black screen with some text flashes on screen, usually around 1-2 minutes after turning on).
